name: Periodic health check

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scheduled_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          # Check the following URLs one by one sequentially
          url: https://full-stack-open-pokedex-raad.onrender.com/health
      - uses: rjstone/discord-webhook-notify@v1.0.0
        if: failure()
        with:
          severity: error
          details: Health check Failed 😱!
          description: Check commit ${{ github.event.head_commit.url }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1.0.0
        if: success()
        with:
          severity: info
          details: Health check successful 🎉!
          description: App is live at https://full-stack-open-pokedex-raad.onrender.com
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
